### ISSUE TITLE
build error yarn2 PnP

### ISSUE THREAD

**Issue by Naia-love** [Assfugil/discord.bio#6]
I still get build error when adding it.
Tho the module works fine, but the problem is when using Travis for exemple, when the install error, the "build" fail

```yarn add discord.bio
➤ YN0000: ┌ Resolution step
➤ YN0060: │ snowflake@workspace:. provides eslint@npm:7.3.0 with version 7.3.0 which doesn't satisfy ^5.0.0 || ^6.0.0 requested by @typescript-eslint/eslint-plugin@npm:2.34.0
➤ YN0060: │ snowflake@workspace:. provides eslint@npm:7.3.0 with version 7.3.0 which doesn't satisfy ^5.0.0 || ^6.0.0 requested by @typescript-eslint/parser@npm:2.34.0
➤ YN0000: └ Completed in 1.26s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ colors@npm:1.4.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ commander@npm:5.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ discord.bio@npm:6.2.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0.27s
➤ YN0000: ┌ Link step
➤ YN0007: │ discord.bio@npm:6.2.1 must be built because it never did before or the last one failed
➤ YN0009: │ discord.bio@npm:6.2.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-b6365d04/build.log)
➤ YN0009: │ discord.bio@npm:6.2.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-b6365d04/build.log)
➤ YN0000: └ Completed in 0.79s
➤ YN0000: Failed with errors in 2.39s
```
and so the log attached 
```
# This file contains the result of Yarn building a package (discord.bio@npm:6.2.1)
# Script name: install

Error: No file matches found: "!". Note: Glob patterns currently only support files that exist on the filesystem (Help Wanted)
    at B (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:438698)
    at async D (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:441488)
    at async v (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:442496)
    at async S (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:442827)
    at async C.exec (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:435855)
    at async Promise.all (index 0)
    at async C.run (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:435981)
    at async D (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:442411)
    at async v (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:442496)
    at async S (/home/naia/Snowflake/.yarn/releases/yarn-berry.js:31:442827)
```

**Comment by Assfugil** [comment]
I just reproduced the issue. Will fix it later since I have pretty busy irl.

**Comment by Assfugil** [comment]
try `yarn add discord.bio@Assfugil/discord.bio#yarn2-pnp-fix`

**Comment by Naia-love** [comment]
```❯ yarn add discord.bio@Assfugil/discord.bio#yarn2-pnp-fix
➤ YN0000: ┌ Resolution step
➤ YN0013: │ discord.bio@https://github.com/Assfugil/discord.bio.git#commit=6c004402e803a95dce1c1e84396a0a5173a9a0c5 can't be found in the cache and will be fetched from GitHub
➤ YN0013: │ discord.bio@https://github.com/Assfugil/discord.bio.git#commit=6c004402e803a95dce1c1e84396a0a5173a9a0c5 can't be found in the cache and will be fetched from the remote repository
➤ YN0001: │ Error: discord.bio@https://github.com/Assfugil/discord.bio.git#commit=6c004402e803a95dce1c1e84396a0a5173a9a0c5: Assertion failed: Unsupported workflow```

**Comment by Naia-love** [comment]
Last version (6.3.0) seems to have fixed it. Thank you
